repos:
- repo: https://github.com/econchick/interrogate
  rev: 1.5.0
  hooks:
    - id: interrogate
      args: [--fail-under=80, --verbose]

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.2.3
  hooks:
    - id: pydocstyle
      args:
          # http://www.pydocstyle.org/en/latest/error_codes.html
          - --ignore=D203,D213

      
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.3.0
  hooks:
    - id: add-trailing-comma
      args: [--py36-plus]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
    - id: mypy
      verbose: true
      additional_dependencies: ['types-requests']

- repo: https://github.com/pycqa/flake8.git
  rev: 3.9.2
  hooks:
  - id: flake8